### PR TITLE
2.0-single

### PR DESCRIPTION
**Pull request by chrisfosterelli**
This builds on @kocolosk's work to add a 2.0 CouchDB image in #52 

Differences:
* The volume mounted in the previous image would always be empty, since CouchDB currently ignores the settings used. This properly uses `/opt/couchdb/data` for the volume.
* Removed an unneeded `couchdb.config` file
* `EXPOSE` ports all on one line
* Name the directory 2.0-single, since it's not actually production.

@klaemo / @kocolosk: I think this fixes a couple of things in the other PR, feel free to review this PR and look at merging it or consider adding these changes to the other PR (whatever makes the most sense). 

@klaemo what are your thoughts on pinning the image to a specific git commit in the CouchDB repository? Although it wouldn't be "production-ready", it would at least lead to a more deterministic build.

I'm happy to make any changes here necessary to help this along :)

### CODE REVIEW

**Comment by klaemo** [comment]
This looks good :) Pinning the image to a specific git commit would be better I think. As long as there is no official release. Could you add that?

Then I will try to merge this in a way that credits both of you @kocolosk and @chrisfosterelli

**Comment by klaemo** [comment]
Oh, and I would highly appreciate a few lines in the Readme about this new image :)

**Comment by chrisfosterelli** [comment]
@klaemo I've pinned this to the latest commit in CouchDB right now ([found here](https://github.com/apache/couchdb/commit/1b38ccd0294ad17d719655612b14b00160168dfd)), and added information to the docs that describes 2.0-single.

Take a look at [the edited docs](https://github.com/chrisfosterelli/docker-couchdb/blob/8d9e616b4ff01e9a2db0a52857d5bb1fefb85a28/README.md) and let me know what you think!

**Comment by klaemo** [comment]
LGTM 👍 I'll take a closer look at it later today and will get this merged. Thanks for your work (both of you)

**Comment by klaemo** [comment]
Merged! Thanks for your work on this @chrisfosterelli :)

It's currently building on Docker Hub

**Comment by chrisfosterelli** [comment]
That's great, thanks @klaemo!

**Comment by klaemo** [comment]
@chrisfosterelli the build on Docker hub failed because of:

```
Cloning into 'couchdb'...
error: pathspec '1b38ccd' did not match any file(s) known to git.
```

**Comment by chrisfosterelli** [comment]
Hm, odd... will take a look when I get in this morning!

**Comment by chrisfosterelli** [comment]
Fixed in #59

**Pull request closed without merging**
