### PR TITLE
Fix erlang solution download path - disable docs

### PR DESCRIPTION
**Pull request by vrince**
I add to disable but it could simply be fixed getting python-sphinx and texlive (I guess) to pass dependencies ...

### CODE REVIEW

**Comment by klaemo** [comment]
Thank you for your PR and welcome to Github :) I'll take a look at it and merge it.

**Comment by vrince** [comment]
Thanks, but it's not so mush really ... at least it compile with that.
Sadly I cannot make a simple couchdb cluster work properly, all instances
are running and working, but /_utils are not reacheable. I'am not sure if
it's due to compilation or if current master state of couchdb repo is
broken.
Best,
Thomas

2015-08-21 9:34 GMT-04:00 Clemens Stolle <notifications@github.com>:

**Comment by klaemo** [comment]
@kxepal what's the state of CouchDB 2.0? I haven't been able to follow along. Has the build step changed?

**Comment by kxepal** [comment]
@klaemo state - we're working on it (:
As about build process, yes, it was some time ago upgraded, but it's still `./configure && make && make install`.

@vrince Missing /_utils may be because Fauxton didn't build.

**Comment by kxepal** [comment]
mmm...I have a question about [this line](https://github.com/klaemo/docker-couchdb/blob/4eed15b1bd5ca5886c836366a3e095d9bda73b23/2.0-dev/Dockerfile#L68) - does it executes the path and shows user what it prints out to stdout, right?

**Comment by klaemo** [comment]
Yes, that's the command that gets run on container startup.

**Comment by kxepal** [comment]
Important moment is about stdout since without arguments dev/run autogenerates random password on every run and prints it back. But so far I don't see any differences from my regular dev usage.

**Comment by vrince** [comment]
@klaemo I'am kind of confused, I simply skip the copy of run.py and let the existing dev/run script as entry point and every thing is running as expected (including fauxton, /_utils endpoints respond properly).

**Comment by klaemo** [comment]
```bash
$ docker run -p 15984:15984 -p 25984:25984 -p 35984:35984 klaemo/couchdb:2.0-dev
Cluster is up, go to http://127.0.0.1:15984/_utils
Object Not Found
```

Hm, I get this and then the container quits :( `Object Not Found` is rather imprecise.

**Comment by vrince** [comment]
Yeah dev/run script seems to fail on cluster check the first time too but is not so worry about that ... and then everything seems up  : 
> [ * ] Check node at http://127.0.0.1:15984/ ... failed: [Errno socket error] [Errno 111] Connection refused
> [ * ] Check node at http://127.0.0.1:25984/ ... ok
> [ * ] Check node at http://127.0.0.1:35984/ ... ok
> [ * ] Check node at http://127.0.0.1:15984/ ... ok

**Comment by kxepal** [comment]
@vrince This failure is safe to ignore: it's simple race condition when script tries to ping node which is still booting up.

**Comment by kxepal** [comment]
@klaemo oh, I see the problem: you replaces dev/run script with out own and yours is a little bit outdated. I'm not sure what exactly caused `Object not found` error, but it's fixed in master long time out.

**Comment by klaemo** [comment]
Yep, just noticed that too. I'm building a fixed version atm. Will report back.

**Comment by klaemo** [comment]
I just committed some the changes to use `master` and get rid of the custom `run.py`. Now it works for me:

```
[ * ] Setup environment ... ok
[ * ] Ensure CouchDB is built ... ok
[ * ] Prepare configuration files ... ok
[ * ] Start node node1 ... ok
[ * ] Start node node2 ... ok
[ * ] Start node node3 ... ok
[ * ] Check node at http://127.0.0.1:15984/ ... failed: [Errno socket error] [Errno 111] Connection refused
[ * ] Check node at http://127.0.0.1:25984/ ... ok
[ * ] Check node at http://127.0.0.1:35984/ ... ok
[ * ] Check node at http://127.0.0.1:15984/ ... ok
[ * ] Running cluster setup ... ok
[ * ] Developers cluster is set up at http://127.0.0.1:15984.
Admin username: root
Password: 37l7YDQJ
Time to hack! ...
```

Note: It might take a few minutes for the changes to propagate to Docker Hub.

**Comment by kxepal** [comment]
@klaemo Cool! Btw, [this](https://github.com/apache/couchdb/commit/587646f1fec6f665f70c97c24f3eef95780b409a) change added haproxy support, so you can add support of it as well (I would like to, but don't have docker support on my system right now) and use good old 5984 port for real clustered requests.

**Pull request closed without merging**
